DIRS=src

CLANLIB_COMPONENTS=Core App Display GL
CLANLIB_VER=2.3

TARGET=clanlib_test


SOURCES=$(foreach dir,${DIRS},$(wildcard ${dir}/*.cpp))
OBJS=$(subst .cpp,.o,${SOURCES})

CLANLIB_PKG_NAMES=$(foreach COMP,${CLANLIB_COMPONENTS},clan${COMP}-${CLANLIB_VER})
CLANLIB_LIBS=$(shell pkg-config --libs ${CLANLIB_PKG_NAMES})
CLANLIB_INCLUDES=$(shell pkg-config --cflags ${CLANLIB_PKG_NAMES})

CXX=g++ 
CXXFLAGS=-Wall -ggdb ${CLANLIB_INCLUDES}

LIBS=${CLANLIB_LIBS} -lpthread

.PHONY: all
all: ${TARGET}

${TARGET}: ${OBJS}
	${CXX} -o $@ $^ ${LIBS}

.PHONY: clean realclean depend
	
depend:
	@makedepend ${SOURCES} -- ${CXXFLAGS} 2> /dev/null
	-rm Makefile.bak

realclean: clean
	-rm ${TARGET}

clean:
	-rm ${OBJS}
# DO NOT DELETE

src/map.o: src/map.h /usr/include/stdlib.h /usr/include/features.h
src/map.o: /usr/include/stdc-predef.h /usr/include/sys/cdefs.h
src/map.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
src/map.o: /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h
src/map.o: /usr/include/endian.h /usr/include/bits/endian.h
src/map.o: /usr/include/bits/byteswap.h /usr/include/bits/byteswap-16.h
src/map.o: /usr/include/sys/types.h /usr/include/bits/types.h
src/map.o: /usr/include/bits/typesizes.h /usr/include/time.h
src/map.o: /usr/include/sys/select.h /usr/include/bits/select.h
src/map.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
src/map.o: /usr/include/sys/sysmacros.h /usr/include/alloca.h src/cell.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/display.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/display.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/api_display.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_types.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_ref8.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/api_core.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_data8.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_ref16.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_data16.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string8.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string16.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/display_target.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/sharedptr.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/system.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_types.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/cl_platform.h
src/map.o: /usr/include/stdint.h /usr/include/bits/wchar.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/weakptr.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/sharedptr.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/setup_display.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/screen_info.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/api_display.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_types.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color_hsv.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color_hsv2.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color_hsv.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color_hsl.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color_hsl2.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/draw.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/graphic_context.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/texture_format.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/sharedptr.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat4.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat2.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat3.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat4.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/angle.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/sharedptr.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/virtual_directory.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/file.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/iodevice.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/databuffer.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/rect.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec2.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/cl_math.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec1.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec3.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec4.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/origin.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/size.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/point.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v0.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/slot.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signals_impl.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/primitives_array.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec3.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/frame_buffer.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/gradient.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/image.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource_data_session.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource_manager.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/weakptr.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/virtual_directory.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/origin.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/image_import_description.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_1.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/exception.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/texture.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/graphic_context.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/compare_function.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/rounded_rect.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/sprite.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/blend_mode.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/collision_outline.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/contour.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_circle.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/point.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_accuracy.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/cl_math.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/circle.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/sprite_description.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_buffer.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_format.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/texture_format.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/buffer_usage.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/subtexture.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/texture_group.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/span_layout.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/size.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/collidable_sprite.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/collision_outline.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/contour.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_accuracy.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_circle.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_math.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_provider_bitmap.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_provider_file.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_description.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_description.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_system.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/subtexture.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_sprite.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_metrics.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_freetype.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_vector.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/palette.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_buffer.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_buffer_help.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_buffer.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_format.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/icon_set.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/perlin_noise.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/image_import_description.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/jpeg_compressor.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/jpeg_decompressor.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/jpeg_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/pcx_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/png_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/provider_factory.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/provider_type.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/provider_type_register.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/provider_type.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/targa_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/blend_mode.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/buffer_control.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/compare_function.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/element_array_buffer.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/vertex_array_buffer.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/buffer_usage.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/frame_buffer.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/graphic_context.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/occlusion_query.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/pen.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/polygon_rasterizer.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/primitives_array.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/primitives_array_builder.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/program_attribute.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/program_object.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/program_uniform.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/render_batcher.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/render_buffer.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/texture.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/shader_object.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/shared_gc_data.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/texture.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/vertex_array_buffer.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/cursor_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/display_target_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/display_window_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/weakptr.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v1.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v2.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_v1.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/display_window.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_0.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/display_target.h
src/map.o: /usr/include/X11/Xlib.h /usr/include/X11/X.h
src/map.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/element_array_buffer_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/element_array_buffer.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/pixel_buffer_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/font_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/frame_buffer_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/frame_buffer.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/graphic_context_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/primitives_array.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/input_device_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_device.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/disposable_object.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/occlusion_query_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/program_object_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/render_buffer_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/render_window_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/shader_object_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/shader_object_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/shader_object.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/texture_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/vertex_array_buffer_provider.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/vertex_array_buffer.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/cursor.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/display_window.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/display_window_description.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_context.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_device.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_event.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_device.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_state.h
src/map.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/keys.h
src/map.o: /usr/include/X11/keysym.h /usr/include/X11/keysymdef.h
src/cell.o: src/cell.h /usr/include/ClanLib-2.3/ClanLib/display.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/display.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/api_display.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_types.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_ref8.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/api_core.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_data8.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_ref16.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_data16.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string8.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string16.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/display_target.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/sharedptr.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/system.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_types.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/cl_platform.h
src/cell.o: /usr/include/stdint.h /usr/include/features.h
src/cell.o: /usr/include/stdc-predef.h /usr/include/sys/cdefs.h
src/cell.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
src/cell.o: /usr/include/bits/wchar.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/weakptr.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/sharedptr.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/setup_display.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/screen_info.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/api_display.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_types.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color_hsv.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color_hsv2.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color_hsv.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color_hsl.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color_hsl2.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/draw.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/graphic_context.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/texture_format.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/sharedptr.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat4.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat2.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat3.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat4.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/angle.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/sharedptr.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/virtual_directory.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/file.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/iodevice.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/databuffer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/rect.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec2.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/cl_math.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec1.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec3.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec4.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/origin.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/size.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/point.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v0.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/slot.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signals_impl.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/primitives_array.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec3.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/frame_buffer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/gradient.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/image.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource_data_session.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource_manager.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/weakptr.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/virtual_directory.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/origin.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/image_import_description.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_1.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/exception.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/texture.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/graphic_context.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/compare_function.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/rounded_rect.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/sprite.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/blend_mode.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/collision_outline.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/contour.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_circle.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/point.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_accuracy.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/cl_math.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/circle.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/sprite_description.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_buffer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_format.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/texture_format.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/buffer_usage.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/subtexture.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/texture_group.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/span_layout.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/size.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/collidable_sprite.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/collision_outline.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/contour.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_accuracy.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_circle.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_math.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_provider_bitmap.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_provider_file.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_description.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_description.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_system.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/subtexture.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_sprite.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_metrics.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_freetype.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_vector.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/palette.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_buffer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_buffer_help.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_buffer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_format.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/icon_set.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/perlin_noise.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/image_import_description.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/jpeg_compressor.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/jpeg_decompressor.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/jpeg_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/pcx_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/png_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/provider_factory.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/provider_type.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/provider_type_register.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/provider_type.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/targa_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/blend_mode.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/buffer_control.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/compare_function.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/element_array_buffer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/vertex_array_buffer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/buffer_usage.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/frame_buffer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/graphic_context.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/occlusion_query.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/pen.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/polygon_rasterizer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/primitives_array.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/primitives_array_builder.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/program_attribute.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/program_object.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/program_uniform.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/render_batcher.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/render_buffer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/texture.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/shader_object.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/shared_gc_data.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/texture.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/vertex_array_buffer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/cursor_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/display_target_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/display_window_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/weakptr.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v1.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v2.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_v1.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/display_window.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_0.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/display_target.h
src/cell.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
src/cell.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
src/cell.o: /usr/include/time.h /usr/include/endian.h
src/cell.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
src/cell.o: /usr/include/bits/byteswap-16.h /usr/include/sys/select.h
src/cell.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
src/cell.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
src/cell.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
src/cell.o: /usr/include/X11/Xosdefs.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/element_array_buffer_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/element_array_buffer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/pixel_buffer_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/font_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/frame_buffer_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/frame_buffer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/graphic_context_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/primitives_array.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/input_device_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_device.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/disposable_object.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/occlusion_query_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/program_object_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/render_buffer_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/render_window_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/shader_object_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/shader_object_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/shader_object.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/texture_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/vertex_array_buffer_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/vertex_array_buffer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/cursor.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/display_window.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/display_window_description.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_context.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_device.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_event.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_device.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_state.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/keys.h
src/cell.o: /usr/include/X11/keysym.h /usr/include/X11/keysymdef.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/core.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/cl_platform.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_types.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/file_logger.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/logger.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_format.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_types.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_help.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/mutex.h
src/cell.o: /usr/include/pthread.h /usr/include/sched.h
src/cell.o: /usr/include/bits/sched.h /usr/include/bits/pthreadtypes.h
src/cell.o: /usr/include/bits/setjmp.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/console.h
src/cell.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
src/cell.o: /usr/include/bits/environments.h /usr/include/bits/confname.h
src/cell.o: /usr/include/getopt.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/console_logger.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/logger.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_format.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_help.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_allocator.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/utf8_reader.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/databuffer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/block_allocator.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/console_window.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/datetime.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/disposable_object.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/event.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/mutex.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/event_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/exception.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/mutex.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/runnable.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/service.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v1.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/setup_core.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/thread.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/runnable.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/exception.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/thread_local_storage.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/uniqueptr.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/weakptr.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/sharedptr.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/system.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/command_line.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/keep_alive.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_0.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_v1.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_2.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/timer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/registry_key.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/interlocked_variable.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_0.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_1.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_2.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_3.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_4.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_5.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_v0.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_v1.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_v2.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_v3.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_v4.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_v5.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v0.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v1.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v2.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v3.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v4.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v5.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/virtual_function_0.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/virtual_function_1.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/virtual_function_2.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/virtual_function_3.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/virtual_function_4.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/virtual_function_5.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/slot.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/slot_container.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v0.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v1.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v2.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v3.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v4.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v5.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource_manager.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource_data_session.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_processing_instruction.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_node.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_string.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_entity_reference.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_notation.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_exception.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_cdata_section.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_text.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_character_data.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_document_fragment.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_comment.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_attr.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_entity.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_document_type.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_document.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_implementation.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_node_list.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_text.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_node.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_character_data.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_named_node_map.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_element.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_string.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/xml_tokenizer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/xml_writer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/xml_token.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/xpath_evaluator.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/xpath_object.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/xpath_object.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/CSS/css_document.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/CSS/css_property.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/CSS/css_tokenizer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/CSS/css_token.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/access_control_list.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/security_identifier.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/file.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/file_help.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/path_help.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/iodevice.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/iodevice_provider.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/pipe_connection.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/pipe_listen.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/security_descriptor.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/access_control_list.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/directory.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/security_identifier.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/cl_endian.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/directory_scanner.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/virtual_directory.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/virtual_file_system.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/virtual_file_source.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/iodevice_memory.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/virtual_directory_listing.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/html_url.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Zip/zip_archive.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Zip/zip_file_entry.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Zip/zip_writer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Zip/zip_reader.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Zip/zip_file_entry.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/angle.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/base64_encoder.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/base64_decoder.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/bezier_curve.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/circle.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec1.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec2.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec3.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec4.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/delauney_triangulator.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/ear_clip_triangulator.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/point.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/ear_clip_result.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/line_math.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/cl_math.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/quaternion.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat2.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat3.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat4.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/origin.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/outline_triangulator.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/point.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/pointset_math.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/circle.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/rect.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/quad.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/rect.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/rect_packer.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/size.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/triangle_math.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/line.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/line_ray.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/line_segment.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/hash_functions.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/sha1.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/random.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/secret.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/sha1.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/md5.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/sha224.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/sha256.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/sha384.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/sha512.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/sha512_224.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/sha512_256.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/aes128_encrypt.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/aes128_decrypt.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/aes192_encrypt.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/aes192_decrypt.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/aes256_encrypt.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/aes256_decrypt.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/rsa.h
src/cell.o: /usr/include/ClanLib-2.3/ClanLib/Core/core_iostream.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/core.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/cl_platform.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_types.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_ref8.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/api_core.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_data8.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_ref16.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_data16.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string8.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string16.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/file_logger.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/logger.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_format.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_types.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_help.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/mutex.h
src/main.o: /usr/include/pthread.h /usr/include/features.h
src/main.o: /usr/include/stdc-predef.h /usr/include/sys/cdefs.h
src/main.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
src/main.o: /usr/include/endian.h /usr/include/bits/endian.h
src/main.o: /usr/include/bits/byteswap.h /usr/include/bits/byteswap-16.h
src/main.o: /usr/include/sched.h /usr/include/bits/types.h
src/main.o: /usr/include/bits/typesizes.h /usr/include/time.h
src/main.o: /usr/include/bits/sched.h /usr/include/bits/pthreadtypes.h
src/main.o: /usr/include/bits/setjmp.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/console.h
src/main.o: /usr/include/unistd.h /usr/include/bits/posix_opt.h
src/main.o: /usr/include/bits/environments.h /usr/include/bits/confname.h
src/main.o: /usr/include/getopt.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/console_logger.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/logger.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_format.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_help.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_allocator.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/sharedptr.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/system.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_types.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/cl_platform.h
src/main.o: /usr/include/stdint.h /usr/include/bits/wchar.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/utf8_reader.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/databuffer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/sharedptr.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/block_allocator.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/console_window.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/datetime.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/disposable_object.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/event.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/mutex.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/event_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/exception.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/mutex.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/runnable.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/service.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v1.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/slot.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signals_impl.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/setup_core.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/thread.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/runnable.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/exception.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/thread_local_storage.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/uniqueptr.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/weakptr.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/sharedptr.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/system.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/command_line.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/keep_alive.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_0.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/exception.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_v1.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_2.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/timer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/registry_key.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/interlocked_variable.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_0.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_1.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_2.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_3.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_4.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_5.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_v0.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_v1.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_v2.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_v3.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_v4.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_v5.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v0.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v1.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v2.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v3.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v4.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v5.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/virtual_function_0.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/virtual_function_1.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/virtual_function_2.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/virtual_function_3.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/virtual_function_4.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/virtual_function_5.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/slot.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/slot_container.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v0.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v1.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v2.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v3.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v4.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v5.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource_manager.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/weakptr.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/virtual_directory.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/file.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/iodevice.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/databuffer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource_manager.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource_data_session.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_processing_instruction.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_node.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_string.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_entity_reference.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_notation.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_exception.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_cdata_section.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_text.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_character_data.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_document_fragment.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_comment.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_attr.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_entity.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_document_type.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_document.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_implementation.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_node_list.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_text.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_node.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_character_data.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_named_node_map.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_element.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/dom_string.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/xml_tokenizer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/xml_writer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/xml_token.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/xpath_evaluator.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/xpath_object.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/XML/xpath_object.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/CSS/css_document.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/CSS/css_property.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/CSS/css_tokenizer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/CSS/css_token.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/access_control_list.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/security_identifier.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/file.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/file_help.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/path_help.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/iodevice.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/iodevice_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/pipe_connection.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/pipe_listen.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/security_descriptor.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/access_control_list.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/directory.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/security_identifier.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/cl_endian.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/directory_scanner.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/virtual_directory.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/virtual_file_system.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/virtual_file_source.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/iodevice_memory.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/virtual_directory_listing.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/html_url.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Zip/zip_archive.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Zip/zip_file_entry.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Zip/zip_writer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Zip/zip_reader.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Zip/zip_file_entry.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/angle.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/base64_encoder.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/base64_decoder.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/bezier_curve.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/circle.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/point.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec2.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/cl_math.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec1.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec3.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec4.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/origin.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/angle.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/size.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec1.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec2.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec3.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec4.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/delauney_triangulator.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/ear_clip_triangulator.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/point.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/ear_clip_result.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/line_math.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/cl_math.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/quaternion.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat2.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat3.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat2.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat4.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat3.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat4.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/origin.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/outline_triangulator.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/point.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/pointset_math.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/circle.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/rect.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/quad.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/rect.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/rect_packer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/size.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/triangle_math.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/line.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/line_ray.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/line_segment.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/hash_functions.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/sha1.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/random.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/secret.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/sha1.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/md5.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/sha224.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/sha256.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/sha384.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/sha512.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/sha512_224.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/sha512_256.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/aes128_encrypt.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/aes128_decrypt.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/aes192_encrypt.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/aes192_decrypt.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/aes256_encrypt.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/aes256_decrypt.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Crypto/rsa.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/core_iostream.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/application.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/App/clanapp.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/App/api_app.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_types.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/display.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/display.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/api_display.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/display_target.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/sharedptr.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/weakptr.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/setup_display.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/screen_info.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/api_display.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Text/string_types.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color_hsv.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color_hsv2.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color_hsv.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color_hsl.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color_hsl2.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/draw.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/graphic_context.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/texture_format.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/sharedptr.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/mat4.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/IOData/virtual_directory.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/rect.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v0.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/primitives_array.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/vec3.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/frame_buffer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/gradient.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/color.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/image.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource_data_session.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/origin.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/image_import_description.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_1.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/texture.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/graphic_context.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/compare_function.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/rounded_rect.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/sprite.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/blend_mode.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/collision_outline.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/contour.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_circle.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/point.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_accuracy.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Resources/resource.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/cl_math.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/circle.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/sprite_description.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_buffer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_format.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/texture_format.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/buffer_usage.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/subtexture.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/texture_group.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/span_layout.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Math/size.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/collidable_sprite.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/collision_outline.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/contour.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_accuracy.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_circle.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_math.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_provider_bitmap.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Collision/outline_provider_file.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_description.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_description.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_system.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/2D/subtexture.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_sprite.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_metrics.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_freetype.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Font/font_vector.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/palette.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_buffer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_buffer_help.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_buffer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_format.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/icon_set.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/perlin_noise.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/image_import_description.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/jpeg_compressor.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/jpeg_decompressor.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/jpeg_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/pcx_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/png_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/provider_factory.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/provider_type.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/provider_type_register.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/provider_type.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/ImageProviders/targa_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/blend_mode.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/buffer_control.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/compare_function.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/element_array_buffer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/vertex_array_buffer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/buffer_usage.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/frame_buffer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/graphic_context.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/occlusion_query.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/pen.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/polygon_rasterizer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/primitives_array.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/primitives_array_builder.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/program_attribute.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/program_object.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/program_uniform.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/render_batcher.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/render_buffer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/texture.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/shader_object.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/shared_gc_data.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/texture.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/vertex_array_buffer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/cursor_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/display_target_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/display_window_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/weakptr.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v1.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/signal_v2.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_v1.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/display_window.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/Signals/callback_0.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/display_target.h
src/main.o: /usr/include/X11/Xlib.h /usr/include/sys/types.h
src/main.o: /usr/include/sys/select.h /usr/include/bits/select.h
src/main.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
src/main.o: /usr/include/sys/sysmacros.h /usr/include/X11/X.h
src/main.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/element_array_buffer_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/element_array_buffer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/pixel_buffer_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/font_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/frame_buffer_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/frame_buffer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/graphic_context_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/primitives_array.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/input_device_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_device.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/disposable_object.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/occlusion_query_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/program_object_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/render_buffer_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/render_window_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/shader_object_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/shader_object_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/shader_object.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/texture_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/TargetProviders/vertex_array_buffer_provider.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/vertex_array_buffer.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/cursor.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/display_window.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/display_window_description.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_context.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_device.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_event.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_device.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/input_state.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/keys.h
src/main.o: /usr/include/X11/keysym.h /usr/include/X11/keysymdef.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/gl.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/GL/opengl.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/GL/api_gl.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/GL/opengl_defines.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Core/System/cl_platform.h
src/main.o: /usr/include/GL/gl.h /usr/include/GL/glext.h
src/main.o: /usr/include/inttypes.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Image/pixel_format.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/texture.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/GL/opengl_defines.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/GL/opengl_target.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/display_target.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/GL/opengl_window_description.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Window/display_window_description.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/GL/opengl_wrap.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/GL/opengl.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/GL/setup_gl.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/GL/opengl_graphic_context.h
src/main.o: /usr/include/ClanLib-2.3/ClanLib/Display/Render/graphic_context.h
src/main.o: src/map.h /usr/include/stdlib.h /usr/include/bits/waitflags.h
src/main.o: /usr/include/bits/waitstatus.h /usr/include/alloca.h src/cell.h
